#! /bin/bash
#
# Cyclotron-svc daemon script
# chkconfig: 2345 50 50
#
 
. /etc/rc.d/init.d/functions

SERVICENAME="cyclotron-svc" 
USER="cyclotron-svc"
DAEMON="node"
ROOT_DIR="/opt/app/cyclotron-svc"
SERVER="$ROOT_DIR/app.js"
LOG_ROOT="$ROOT_DIR/log"
LOG_FILE="$LOG_ROOT/app.log"
LOCK_ROOT="/var/lock/subsys"
LOCK_FILE="$LOCK_ROOT/$SERVICENAME"

mkdir -p $LOG_ROOT
mkdir -p $LOCK_ROOT
 
function startService {
    if [ ! -f "$LOCK_FILE" ] ; then
    echo -n $"Starting $SERVICENAME: "
    cd $ROOT_DIR
    daemon --user="$USER" forever start --workingDir $ROOT_DIR -a -o $LOG_FILE -l $LOG_ROOT/forever.log --minUptime 1000 --spinSleepTime 2000 $SERVER
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    else
    echo "$SERVICENAME is already running."
    RETVAL=1
    fi
}

function stopService {
    echo -n $"Stopping $SERVICENAME: "
    cd $ROOT_DIR
    daemon --user="$USER" forever stop $SERVER && echo_success || echo_failure
    RETVAL=$?
    echo
    rm -f $LOCK_FILE
}

function main { 
    RETVAL=0
    case "$1" in
        start)
            startService
            ;;
        stop)
            stopService
            ;;
        restart)
            stopService && startService
            ;;
        *)
            echo "Usage: $0 {start|stop|restart}"
            RETVAL=1
            ;;
    esac
 
    exit $RETVAL
}

main $1
